### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by m0s30** [smilexxfire/GoogleDorkScan#1]
师傅，扫描时间长了，会超时，提示请求次数过多
![image](https://github.com/smilexxfire/GoogleDorkScan/assets/54650671/84f4151b-ad76-4f31-9c3b-67a1cdd52bb9)

**Comment by smilexxfire** [comment]
> 师傅，扫描时间长了，会超时，提示请求次数过多 ![image](https://private-user-images.githubusercontent.com/54650671/321849939-84f4151b-ad76-4f31-9c3b-67a1cdd52bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDYzMDcsIm5iZiI6MTcxMjkwNjAwNywicGF0aCI6Ii81NDY1MDY3MS8zMjE4NDk5MzktODRmNDE1MWItYWQ3Ni00ZjMxLTljM2ItNjdhMWNkZDUyYmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjYzYjBkZTdlMDg1YjRiNWIyMzY3ZjIzNjM1ODJkNzM1ZjFjOGQ0Mzc1Yzk2YzZkNzYxYTFhNWE3NWVmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JGK35p5KSD1lwMEZqKXZhDboSSIWGfSQWlptZ1iF9Go)

google查询频繁了，只能等或者换ip，后面版本会添加代理支持

**Comment by smilexxfire** [comment]
https://github.com/MarioVilas/googlesearch/issues/98
